import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const users = [
  { userId: "USR-001", name: "Alex Rivera", email: "alex.rivera@company.com", role: "Development Manager", department: "IT", manager: "CTO Office", accessLevel: "Admin", status: "Active", lastLogin: new Date("2026-06-25") },
  { userId: "USR-002", name: "Jordan Lee", email: "jordan.lee@company.com", role: "Development Manager", department: "IT", manager: "CTO Office", accessLevel: "Admin", status: "Active", lastLogin: new Date("2026-06-25") },
  { userId: "USR-003", name: "Casey Chen", email: "casey.chen@company.com", role: "Development Manager", department: "IT", manager: "CTO Office", accessLevel: "Admin", status: "Active", lastLogin: new Date("2026-06-24") },
  { userId: "USR-004", name: "Morgan Taylor", email: "morgan.taylor@company.com", role: "Development Manager", department: "IT", manager: "CTO Office", accessLevel: "Admin", status: "Active", lastLogin: new Date("2026-06-25") },
  { userId: "USR-005", name: "Jamie Patel", email: "jamie.patel@company.com", role: "Development Manager", department: "IT", manager: "CTO Office", accessLevel: "Admin", status: "Active", lastLogin: new Date("2026-06-24") },
  { userId: "USR-006", name: "Riley Kim", email: "riley.kim@company.com", role: "Development Manager", department: "IT", manager: "CTO Office", accessLevel: "Admin", status: "Active", lastLogin: new Date("2026-06-25") },
  { userId: "USR-007", name: "Quinn Johnson", email: "quinn.johnson@company.com", role: "Development Manager", department: "IT", manager: "CTO Office", accessLevel: "Admin", status: "Active", lastLogin: new Date("2026-06-23") },
  { userId: "USR-008", name: "Avery Williams", email: "avery.williams@company.com", role: "Development Manager", department: "IT", manager: "CTO Office", accessLevel: "Admin", status: "Active", lastLogin: new Date("2026-06-25") },
  { userId: "USR-009", name: "Drew Martinez", email: "drew.martinez@company.com", role: "Development Manager", department: "IT", manager: "CTO Office", accessLevel: "Admin", status: "Active", lastLogin: new Date("2026-06-24") },
  { userId: "USR-010", name: "Cameron Brown", email: "cameron.brown@company.com", role: "Development Manager", department: "IT", manager: "CTO Office", accessLevel: "Admin", status: "Active", lastLogin: new Date("2026-06-25") },
  { userId: "USR-011", name: "Taylor Singh", email: "taylor.singh@company.com", role: "Development Manager", department: "IT", manager: "CTO Office", accessLevel: "Admin", status: "Active", lastLogin: new Date("2026-06-22") },
  { userId: "USR-012", name: "Blake Thompson", email: "blake.thompson@company.com", role: "Development Manager", department: "IT", manager: "CTO Office", accessLevel: "Admin", status: "Active", lastLogin: new Date("2026-06-25") },
  { userId: "USR-013", name: "Sam Anderson", email: "sam.anderson@company.com", role: "QA Lead", department: "QA", manager: "QA Director", accessLevel: "Standard", status: "Active", lastLogin: new Date("2026-06-25") },
  { userId: "USR-014", name: "Chris Park", email: "chris.park@company.com", role: "QA Lead", department: "QA", manager: "QA Director", accessLevel: "Standard", status: "Active", lastLogin: new Date("2026-06-25") },
  { userId: "USR-015", name: "Pat Murphy", email: "pat.murphy@company.com", role: "QA Lead", department: "QA", manager: "QA Director", accessLevel: "Standard", status: "Active", lastLogin: new Date("2026-06-24") },
  { userId: "USR-016", name: "Jesse Garcia", email: "jesse.garcia@company.com", role: "QA Lead", department: "QA", manager: "QA Director", accessLevel: "Standard", status: "Active", lastLogin: new Date("2026-06-25") },
  { userId: "USR-017", name: "Robin Chen", email: "robin.chen@company.com", role: "QA Lead", department: "QA", manager: "QA Director", accessLevel: "Standard", status: "Active", lastLogin: new Date("2026-06-23") },
  { userId: "USR-018", name: "Dana Wilson", email: "dana.wilson@company.com", role: "QA Lead", department: "QA", manager: "QA Director", accessLevel: "Standard", status: "Active", lastLogin: new Date("2026-06-25") },
  { userId: "USR-019", name: "Kelly Nguyen", email: "kelly.nguyen@company.com", role: "QA Lead", department: "QA", manager: "QA Director", accessLevel: "Standard", status: "Active", lastLogin: new Date("2026-06-24") },
  { userId: "USR-020", name: "Terry Brooks", email: "terry.brooks@company.com", role: "QA Lead", department: "QA", manager: "QA Director", accessLevel: "Standard", status: "Active", lastLogin: new Date("2026-06-25") },
  { userId: "USR-021", name: "Skyler Davis", email: "skyler.davis@company.com", role: "QA Lead", department: "QA", manager: "QA Director", accessLevel: "Standard", status: "Active", lastLogin: new Date("2026-06-25") },
  { userId: "USR-022", name: "Jordan Reed", email: "jordan.reed@company.com", role: "QA Lead", department: "QA", manager: "QA Director", accessLevel: "Standard", status: "Active", lastLogin: new Date("2026-06-22") },
  { userId: "USR-023", name: "Alex Foster", email: "alex.foster@company.com", role: "QA Lead", department: "QA", manager: "QA Director", accessLevel: "Standard", status: "Active", lastLogin: new Date("2026-06-25") },
  { userId: "USR-024", name: "Morgan Hayes", email: "morgan.hayes@company.com", role: "QA Lead", department: "QA", manager: "QA Director", accessLevel: "Standard", status: "Active", lastLogin: new Date("2026-06-24") },
  { userId: "USR-025", name: "Rachel Green", email: "rachel.green@company.com", role: "Business Analyst", department: "Business Ops", manager: "BA Manager", accessLevel: "Standard", status: "Active", lastLogin: new Date("2026-06-25") },
  { userId: "USR-026", name: "Monica Geller", email: "monica.geller@company.com", role: "Business Analyst", department: "Business Ops", manager: "BA Manager", accessLevel: "Standard", status: "Active", lastLogin: new Date("2026-06-25") },
  { userId: "USR-027", name: "Phoebe Buffay", email: "phoebe.buffay@company.com", role: "Business Analyst", department: "Business Ops", manager: "BA Manager", accessLevel: "Standard", status: "Active", lastLogin: new Date("2026-06-24") },
  { userId: "USR-028", name: "Emma Watson", email: "emma.watson@company.com", role: "Business Analyst", department: "Business Ops", manager: "BA Manager", accessLevel: "Standard", status: "Active", lastLogin: new Date("2026-06-25") },
  { userId: "USR-029", name: "Sophie Turner", email: "sophie.turner@company.com", role: "Business Analyst", department: "Business Ops", manager: "BA Manager", accessLevel: "Standard", status: "Active", lastLogin: new Date("2026-06-23") },
  { userId: "USR-030", name: "Mia Collins", email: "mia.collins@company.com", role: "Business Analyst", department: "Business Ops", manager: "BA Manager", accessLevel: "Standard", status: "Active", lastLogin: new Date("2026-06-25") },
  { userId: "USR-031", name: "Isabella Moore", email: "isabella.moore@company.com", role: "Business Analyst", department: "Business Ops", manager: "BA Manager", accessLevel: "Standard", status: "Active", lastLogin: new Date("2026-06-24") },
  { userId: "USR-032", name: "Olivia James", email: "olivia.james@company.com", role: "Business Analyst", department: "Business Ops", manager: "BA Manager", accessLevel: "Standard", status: "Active", lastLogin: new Date("2026-06-25") },
  { userId: "USR-033", name: "Ava Mitchell", email: "ava.mitchell@company.com", role: "Business Analyst", department: "Business Ops", manager: "BA Manager", accessLevel: "Standard", status: "Active", lastLogin: new Date("2026-06-25") },
  { userId: "USR-034", name: "Charlotte Price", email: "charlotte.price@company.com", role: "Business Analyst", department: "Business Ops", manager: "BA Manager", accessLevel: "Standard", status: "Active", lastLogin: new Date("2026-06-22") },
  { userId: "USR-035", name: "Amelia Scott", email: "amelia.scott@company.com", role: "Business Analyst", department: "Business Ops", manager: "BA Manager", accessLevel: "Standard", status: "Active", lastLogin: new Date("2026-06-25") },
  { userId: "USR-036", name: "Harper Lewis", email: "harper.lewis@company.com", role: "Business Analyst", department: "Business Ops", manager: "BA Manager", accessLevel: "Standard", status: "Active", lastLogin: new Date("2026-06-24") },
  { userId: "USR-037", name: "Nathan Cole", email: "nathan.cole@company.com", role: "Release Manager", department: "IT", manager: "IT Director", accessLevel: "Admin", status: "Active", lastLogin: new Date("2026-06-25") },
  { userId: "USR-038", name: "Ethan Black", email: "ethan.black@company.com", role: "Release Manager", department: "IT", manager: "IT Director", accessLevel: "Admin", status: "Active", lastLogin: new Date("2026-06-25") },
  { userId: "USR-039", name: "Lucas White", email: "lucas.white@company.com", role: "Release Manager", department: "IT", manager: "IT Director", accessLevel: "Admin", status: "Active", lastLogin: new Date("2026-06-24") },
  { userId: "USR-040", name: "Mason Gray", email: "mason.gray@company.com", role: "Release Manager", department: "IT", manager: "IT Director", accessLevel: "Admin", status: "Active", lastLogin: new Date("2026-06-25") },
  { userId: "USR-041", name: "Logan Stone", email: "logan.stone@company.com", role: "Release Manager", department: "IT", manager: "IT Director", accessLevel: "Admin", status: "Active", lastLogin: new Date("2026-06-23") },
  { userId: "USR-042", name: "Jacob Hill", email: "jacob.hill@company.com", role: "Release Manager", department: "IT", manager: "IT Director", accessLevel: "Admin", status: "Active", lastLogin: new Date("2026-06-25") },
  { userId: "USR-043", name: "Aiden Clark", email: "aiden.clark@company.com", role: "Release Manager", department: "IT", manager: "IT Director", accessLevel: "Admin", status: "Active", lastLogin: new Date("2026-06-24") },
  { userId: "USR-044", name: "Jackson Moore", email: "jackson.moore@company.com", role: "Release Manager", department: "IT", manager: "IT Director", accessLevel: "Admin", status: "Active", lastLogin: new Date("2026-06-25") },
  { userId: "USR-045", name: "Sebastian Hall", email: "sebastian.hall@company.com", role: "Release Manager", department: "IT", manager: "IT Director", accessLevel: "Admin", status: "Active", lastLogin: new Date("2026-06-25") },
  { userId: "USR-046", name: "Caleb Young", email: "caleb.young@company.com", role: "Release Manager", department: "IT", manager: "IT Director", accessLevel: "Admin", status: "Active", lastLogin: new Date("2026-06-22") },
  { userId: "USR-047", name: "Owen King", email: "owen.king@company.com", role: "Release Manager", department: "IT", manager: "IT Director", accessLevel: "Admin", status: "Active", lastLogin: new Date("2026-06-25") },
  { userId: "USR-048", name: "Liam Wright", email: "liam.wright@company.com", role: "Release Manager", department: "IT", manager: "IT Director", accessLevel: "Admin", status: "Active", lastLogin: new Date("2026-06-24") },
  { userId: "USR-049", name: "Victoria Sterling", email: "victoria.sterling@company.com", role: "Operations Manager", department: "Operations", manager: "VP Operations", accessLevel: "Admin", status: "Active", lastLogin: new Date("2026-06-25") },
  { userId: "USR-050", name: "Elizabeth Crown", email: "elizabeth.crown@company.com", role: "Operations Manager", department: "Operations", manager: "VP Operations", accessLevel: "Admin", status: "Active", lastLogin: new Date("2026-06-25") },
  { userId: "USR-051", name: "Catherine Royal", email: "catherine.royal@company.com", role: "Operations Manager", department: "Operations", manager: "VP Operations", accessLevel: "Admin", status: "Active", lastLogin: new Date("2026-06-24") },
  { userId: "USR-052", name: "Margaret Noble", email: "margaret.noble@company.com", role: "Operations Manager", department: "Operations", manager: "VP Operations", accessLevel: "Admin", status: "Active", lastLogin: new Date("2026-06-25") },
  { userId: "USR-053", name: "Diana Prince", email: "diana.prince@company.com", role: "Operations Manager", department: "Operations", manager: "VP Operations", accessLevel: "Admin", status: "Active", lastLogin: new Date("2026-06-23") },
  { userId: "USR-054", name: "Helena Troy", email: "helena.troy@company.com", role: "Operations Manager", department: "Operations", manager: "VP Operations", accessLevel: "Admin", status: "Active", lastLogin: new Date("2026-06-25") },
  { userId: "USR-055", name: "Sophia Grace", email: "sophie.grace@company.com", role: "Operations Manager", department: "Operations", manager: "VP Operations", accessLevel: "Admin", status: "Active", lastLogin: new Date("2026-06-24") },
  { userId: "USR-056", name: "Alexandra Reid", email: "alexandra.reid@company.com", role: "Operations Manager", department: "Operations", manager: "VP Operations", accessLevel: "Admin", status: "Active", lastLogin: new Date("2026-06-25") },
  { userId: "USR-057", name: "Christina Vale", email: "christina.vale@company.com", role: "Operations Manager", department: "Operations", manager: "VP Operations", accessLevel: "Admin", status: "Active", lastLogin: new Date("2026-06-25") },
  { userId: "USR-058", name: "Natasha Roman", email: "natasha.roman@company.com", role: "Operations Manager", department: "Operations", manager: "VP Operations", accessLevel: "Admin", status: "Active", lastLogin: new Date("2026-06-22") },
  { userId: "USR-059", name: "Amanda Cross", email: "amanda.cross@company.com", role: "Operations Manager", department: "Operations", manager: "VP Operations", accessLevel: "Admin", status: "Active", lastLogin: new Date("2026-06-25") },
  { userId: "USR-060", name: "Rebecca Stone", email: "rebecca.stone@company.com", role: "Operations Manager", department: "Operations", manager: "VP Operations", accessLevel: "Admin", status: "Active", lastLogin: new Date("2026-06-24") },
  { userId: "USR-061", name: "Robert Shield", email: "robert.shield@company.com", role: "Infrastructure Lead", department: "Infrastructure", manager: "Infra Director", accessLevel: "Admin", status: "Active", lastLogin: new Date("2026-06-25") },
  { userId: "USR-062", name: "William Guard", email: "william.guard@company.com", role: "Infrastructure Lead", department: "Infrastructure", manager: "Infra Director", accessLevel: "Admin", status: "Active", lastLogin: new Date("2026-06-25") },
  { userId: "USR-063", name: "James Fortress", email: "james.fortress@company.com", role: "Infrastructure Lead", department: "Infrastructure", manager: "Infra Director", accessLevel: "Admin", status: "Active", lastLogin: new Date("2026-06-24") },
  { userId: "USR-064", name: "Michael Bastion", email: "michael.bastion@company.com", role: "Infrastructure Lead", department: "Infrastructure", manager: "Infra Director", accessLevel: "Admin", status: "Active", lastLogin: new Date("2026-06-25") },
  { userId: "USR-065", name: "David Tower", email: "david.tower@company.com", role: "Infrastructure Lead", department: "Infrastructure", manager: "Infra Director", accessLevel: "Admin", status: "Active", lastLogin: new Date("2026-06-23") },
  { userId: "USR-066", name: "Richard Wall", email: "richard.wall@company.com", role: "Infrastructure Lead", department: "Infrastructure", manager: "Infra Director", accessLevel: "Admin", status: "Active", lastLogin: new Date("2026-06-25") },
  { userId: "USR-067", name: "Thomas Castle", email: "thomas.castle@company.com", role: "Infrastructure Lead", department: "Infrastructure", manager: "Infra Director", accessLevel: "Admin", status: "Active", lastLogin: new Date("2026-06-24") },
  { userId: "USR-068", name: "Charles Vault", email: "charles.vault@company.com", role: "Infrastructure Lead", department: "Infrastructure", manager: "Infra Director", accessLevel: "Admin", status: "Active", lastLogin: new Date("2026-06-25") },
  { userId: "USR-069", name: "Daniel Bunker", email: "daniel.bunker@company.com", role: "Infrastructure Lead", department: "Infrastructure", manager: "Infra Director", accessLevel: "Admin", status: "Active", lastLogin: new Date("2026-06-25") },
  { userId: "USR-070", name: "Matthew Haven", email: "matthew.haven@company.com", role: "Infrastructure Lead", department: "Infrastructure", manager: "Infra Director", accessLevel: "Admin", status: "Active", lastLogin: new Date("2026-06-22") },
  { userId: "USR-071", name: "Anthony Secure", email: "anthony.secure@company.com", role: "Infrastructure Lead", department: "Infrastructure", manager: "Infra Director", accessLevel: "Admin", status: "Active", lastLogin: new Date("2026-06-25") },
  { userId: "USR-072", name: "Mark Backup", email: "mark.backup@company.com", role: "Infrastructure Lead", department: "Infrastructure", manager: "Infra Director", accessLevel: "Admin", status: "Active", lastLogin: new Date("2026-06-24") },
  { userId: "USR-073", name: "Sarah Mitchell", email: "sarah.mitchell@company.com", role: "Application Owner", department: "Finance", manager: "Finance Director", accessLevel: "Standard", status: "Active", lastLogin: new Date("2026-06-25") },
  { userId: "USR-074", name: "David Chen", email: "david.chen@company.com", role: "Application Owner", department: "Finance", manager: "Finance Director", accessLevel: "Standard", status: "Active", lastLogin: new Date("2026-06-24") },
  { userId: "USR-075", name: "Brian Murphy", email: "brian.murphy@company.com", role: "Application Owner", department: "Logistics", manager: "Logistics Director", accessLevel: "Standard", status: "Active", lastLogin: new Date("2026-06-25") },
  { userId: "USR-076", name: "Matthew Clarke", email: "matthew.clarke@company.com", role: "Application Owner", department: "CRM", manager: "Sales Director", accessLevel: "Standard", status: "Active", lastLogin: new Date("2026-06-23") },
  { userId: "USR-077", name: "Richard Hoffman", email: "richard.hoffman@company.com", role: "Application Owner", department: "Manufacturing", manager: "Mfg Director", accessLevel: "Standard", status: "Active", lastLogin: new Date("2026-06-25") },
  { userId: "USR-078", name: "Christopher Blake", email: "christopher.blake@company.com", role: "Application Owner", department: "IT", manager: "IT Director", accessLevel: "Standard", status: "Active", lastLogin: new Date("2026-06-24") },
  { userId: "USR-079", name: "Daniel Crawford", email: "daniel.crawford@company.com", role: "Application Owner", department: "HR", manager: "HR Director", accessLevel: "Standard", status: "Active", lastLogin: new Date("2026-06-25") },
  { userId: "USR-080", name: "Howard Blackwell", email: "howard.blackwell@company.com", role: "Application Owner", department: "Legal", manager: "Legal Director", accessLevel: "Standard", status: "Active", lastLogin: new Date("2026-06-25") },
  { userId: "USR-081", name: "Charles Hamilton", email: "charles.hamilton@company.com", role: "Application Owner", department: "Security", manager: "CISO", accessLevel: "Standard", status: "Active", lastLogin: new Date("2026-06-22") },
  { userId: "USR-082", name: "James Wilson", email: "james.wilson@company.com", role: "Tech Lead", department: "Finance", manager: "App Owner", accessLevel: "Standard", status: "Active", lastLogin: new Date("2026-06-25") },
  { userId: "USR-083", name: "Marcus Johnson", email: "marcus.johnson@company.com", role: "Tech Lead", department: "Logistics", manager: "App Owner", accessLevel: "Standard", status: "Active", lastLogin: new Date("2026-06-24") },
  { userId: "USR-084", name: "Carlos Mendez", email: "carlos.mendez@company.com", role: "Tech Lead", department: "CRM", manager: "App Owner", accessLevel: "Standard", status: "Active", lastLogin: new Date("2026-06-25") },
  { userId: "USR-085", name: "Kenneth Wright", email: "kenneth.wright@company.com", role: "Tech Lead", department: "Manufacturing", manager: "App Owner", accessLevel: "Standard", status: "Active", lastLogin: new Date("2026-06-23") },
  { userId: "USR-086", name: "Jeffrey Kumar", email: "jeffrey.kumar@company.com", role: "Tech Lead", department: "IT", manager: "App Owner", accessLevel: "Standard", status: "Active", lastLogin: new Date("2026-06-25") },
  { userId: "USR-087", name: "Nicholas Chen", email: "nicholas.chen@company.com", role: "Tech Lead", department: "HR", manager: "App Owner", accessLevel: "Standard", status: "Active", lastLogin: new Date("2026-06-24") },
  { userId: "USR-088", name: "Michael Sterling", email: "michael.sterling@company.com", role: "CTO", department: "Executive", manager: "CEO", accessLevel: "Executive", status: "Active", lastLogin: new Date("2026-06-25") },
  { userId: "USR-089", name: "Jennifer Morrison", email: "jennifer.morrison@company.com", role: "CIO", department: "Executive", manager: "CEO", accessLevel: "Executive", status: "Active", lastLogin: new Date("2026-06-25") },
  { userId: "USR-090", name: "Robert Anderson", email: "robert.anderson@company.com", role: "CFO", department: "Executive", manager: "CEO", accessLevel: "Executive", status: "Active", lastLogin: new Date("2026-06-22") },
  { userId: "USR-091", name: "Linda Prescott", email: "linda.prescott@company.com", role: "VP Engineering", department: "IT", manager: "CTO", accessLevel: "Executive", status: "Active", lastLogin: new Date("2026-06-25") },
  { userId: "USR-092", name: "Thomas Reynolds", email: "thomas.reynolds@company.com", role: "VP Operations", department: "Operations", manager: "COO", accessLevel: "Executive", status: "Active", lastLogin: new Date("2026-06-24") },
  { userId: "USR-093", name: "Emily Zhang", email: "emily.zhang@company.com", role: "Senior Developer", department: "IT", manager: "Dev Manager", accessLevel: "Standard", status: "Active", lastLogin: new Date("2026-06-25") },
  { userId: "USR-094", name: "Michael Brown", email: "michael.brown@company.com", role: "Senior Developer", department: "IT", manager: "Dev Manager", accessLevel: "Standard", status: "Active", lastLogin: new Date("2026-06-23") },
  { userId: "USR-095", name: "Priya Sharma", email: "priya.sharma@company.com", role: "Database Admin", department: "IT", manager: "Infra Lead", accessLevel: "Standard", status: "Active", lastLogin: new Date("2026-06-25") },
  { userId: "USR-096", name: "Angela Liu", email: "angela.liu@company.com", role: "Systems Analyst", department: "IT", manager: "BA Manager", accessLevel: "Standard", status: "Active", lastLogin: new Date("2026-06-24") },
  { userId: "USR-097", name: "Ryan Cooper", email: "ryan.cooper@company.com", role: "DevOps Engineer", department: "IT", manager: "Infra Lead", accessLevel: "Standard", status: "Active", lastLogin: new Date("2026-06-25") },
  { userId: "USR-098", name: "Jessica Nguyen", email: "jessica.nguyen@company.com", role: "Security Analyst", department: "Security", manager: "CISO", accessLevel: "Standard", status: "Active", lastLogin: new Date("2026-06-25") },
  { userId: "USR-099", name: "Brandon Lee", email: "brandon.lee@company.com", role: "Network Engineer", department: "IT", manager: "Infra Lead", accessLevel: "Standard", status: "Active", lastLogin: new Date("2026-06-22") },
  { userId: "USR-100", name: "Michelle Davis", email: "michelle.davis@company.com", role: "Project Manager", department: "PMO", manager: "PMO Director", accessLevel: "Standard", status: "Active", lastLogin: new Date("2026-06-25") },
];

async function main() {
  console.log("Seeding exact user data...");
  for (const user of users) {
    await prisma.user.upsert({
      where: { userId: user.userId },
      update: user,
      create: user,
    });
  }
  console.log("Successfully seeded 100 users.");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
